//! Browser build of the `image` VGI worker.
//!
//! Compiled to `wasm32-unknown-emscripten` and linked by `emcc` into a Web
//! Worker module (see `wasm/build.sh`). DuckDB-WASM's VGI extension delivers a
//! SharedArrayBuffer channel; each ring slot gets a serve thread that hands the
//! byte stream to the *same* [`image_worker::build_worker`] the native binary
//! uses — only the transport differs (`serve_reader_writer` instead of `run`).
//!
//! The canonical `worker:` entry points (`vgi_worker_init`,
//! `vgi_worker_serve_sab_slot`, `vgi_worker_serve_pool`) — plus the SAB ring
//! shims and panic-catching — are generated by the `vgi::wasm_worker!` SDK
//! macro; only the `wasm_init` hook below is worker-specific.

/// Select the in-memory shared-storage backend before any function runs: the
/// default filesystem backend writes to a temp dir that does not exist under
/// emscripten's MEMFS, and there is no second process to share state with. Runs
/// on the module main thread (env var only — safe off a serve thread).
#[cfg(target_arch = "wasm32")]
fn wasm_init() {
    if std::env::var_os("VGI_WORKER_SHARED_STORAGE").is_none() {
        std::env::set_var("VGI_WORKER_SHARED_STORAGE", "memory");
    }
}

vgi::wasm_worker! {
    init = wasm_init,
    build = image_worker::build_worker,
}
