#!/usr/bin/env bash
# Exports hapai guardrails as GitHub Copilot instructions (.github/copilot-instructions.md)
set -euo pipefail

HAPAI_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RULES_BODY="$(cat "$HAPAI_ROOT/templates/guardrails-rules.md")"

mkdir -p .github

cat > .github/copilot-instructions.md << RULES
# Hapai Guardrails for GitHub Copilot
<!-- Generated by: hapai export --target copilot -->

$RULES_BODY
RULES

echo ".github/copilot-instructions.md"
