"""CC0 AVIF container transforms generated by libavif from EXIF orientation.
Pillow decodes stored pixels; ImageOps.exif_transpose is the independent oracle.
"""
from pathlib import Path
import hashlib
from PIL import Image,ImageOps
root=Path(__file__).resolve().parent.parent/'tests/fixtures/raster'
image=Image.new('RGB',(8,4));image.putdata([(x*31,y*63,(x+y)*17) for y in range(4) for x in range(8)])
lines=[l for l in (root/'manifest.tsv').read_text().splitlines() if not l.startswith('avif-orientation-')]
for orientation in range(2,9):
 name=f'avif-orientation-{orientation}.avif';path=root/name;exif=Image.Exif();exif[274]=orientation
 image.save(path,format='AVIF',quality=100,subsampling='4:4:4',exif=exif)
 with Image.open(path) as decoded:
  corrected=ImageOps.exif_transpose(decoded);oracle=corrected.convert('RGBA').tobytes();w,h=corrected.size
 (root/(name+'.rgba')).write_bytes(oracle)
 lines.append(f'{name}\t{w}\t{h}\t3\t{name}.rgba\t{hashlib.sha256(path.read_bytes()).hexdigest()}')
(root/'manifest.tsv').write_text('\n'.join(lines)+'\n')
