"""Recheck all42 budget refusals with bounded complete original point capacity."""
import hashlib,json,shutil,subprocess
from pathlib import Path
D=Path('docs/research');T=Path('/Users/themoretheless/.codex/tmp/rrrah-dedup-copydays');h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();baseline=D/'dedup-main-all-photometric-local-rank.json';r=json.loads(baseline.read_text());old=next(x for x in r['results'] if x['query']=='207401.jpg');assert len(old['regions'])==14 and all(e['status']=='refusal:Budget' for region in old['regions'] for e in region['evidence']);exe=T/'local-rank-cached-large-points-probe-qualified';assert not exe.exists();shutil.copy2('target/release/examples/local_rank_cached_large_points_probe',exe);work=T/'all-photometric-local-rank';pixels=[work/f'{x}.rgba32' for x in ['207400','207401']];points=work/'207401-points.txt';assert len(points.read_text().splitlines())==1016
files=[baseline,exe,points,*pixels,Path(__file__),Path('crates/rrrah-dedup/examples/local_rank_cached_large_points_probe.rs'),Path('crates/rrrah-dedup/src/local_rank.rs')];files.extend(work/f"207401-{v['region_index']}-model.txt" for v in old['regions']);pins={str(p):h(p) for p in files};out=D/'dedup-main-local-rank-large-points.json';assert not out.exists();report={'status':'running','query':'207401.jpg','points':1016,'maximum_points':28000,'maximum_point_checks':392014000,'required_regions':14,'results':[],'input_hashes':pins,'scope':'Same fixed model/regions/pixels/all1016 original points; only prepaid maximum point count/check budget raised to canonical28000 ceiling. No inlier/residual/pixel/coverage threshold change, no default promotion.'}
for region in old['regions']:
 model=work/f"207401-{region['region_index']}-model.txt";p=subprocess.run([str(exe),*map(str,pixels),str(model),str(points)],capture_output=True,text=True);v={'region_index':region['region_index'],'expected_witnesses':len(region['witness_indices']),'returncode':p.returncode,'stdout':p.stdout,'stderr':p.stderr}
 if p.returncode==0:v['evidence']=[json.loads(x) for x in p.stdout.splitlines()]
 report['results'].append(v);out.write_text(json.dumps(report,indent=2)+'\n')
assert all(h(p)==v for p,v in pins.items());report['status']='complete';out.write_text(json.dumps(report,indent=2)+'\n')
