"""Pinned native decoder/mapped-filter/held-out color probe for fixed screen ROI."""
import hashlib,json,subprocess,shutil
from pathlib import Path
root=Path('/Users/themoretheless/.codex/tmp/rrrah-dedup-copydays');b=Path('docs/research');h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();exe=root/'affine-color-image-probe-screen';assert not exe.exists();shutil.copy2('target/debug/examples/affine_color_image_probe',exe)
left=root/'original-resolution-negative-200201/200500.jpg';right=root/'original-resolution-strong-all/200501.jpg';input=b/'dedup-screen-global-translation-anchor.txt';baseline=b/'dedup-screen-filter8.json';r0=json.loads(baseline.read_text());assert all(h(k)==v for k,v in r0['input_hashes'].items());assert [float(v) for v in input.read_text().split()]==[v for row in r0['evidence']['matrix'] for v in row];manifest=root/'prepared.json';m=json.loads(manifest.read_text())
for path,split in [(left,'original'),(right,'strong')]:assert h(path)==next(v['source_sha256'] for v in m['images'][split] if v['filename']==path.name)
pins={str(p):h(p) for p in [exe,left,right,input,baseline,manifest,Path(__file__),Path('crates/rrrah-dedup/examples/affine_color_image_probe.rs'),Path('crates/rrrah-dedup/src/affine_color.rs')]};out=b/'dedup-native-screen-affine-color.json';assert not out.exists();r={'status':'running_native','input_hashes':pins,'required_directions':2,'forward_roi':[240,60,80,60],'reverse_roi':[2115,922,103,133],'filter_radius':8,'tolerance':0.03,'minimum_variance':1e-5,'maximum_coefficient':5,'maximum_offset':.1,'scope':'Native rrrah decoding and mapped-linear box samples in both directions; disjoint8x8 checker training/heldout. Fixed known ROI, no negative image controls or default promotion; sample vectors separately bounded outside decode credit.'}
def save():
 tmp=out.with_suffix('.tmp');tmp.write_text(json.dumps(r,indent=2)+'\n');tmp.replace(out)
save();v=subprocess.run([str(exe),str(left),str(right),str(input)],capture_output=True,text=True);assert all(h(k)==v for k,v in pins.items());r.update(returncode=v.returncode,stdout=v.stdout,stderr=v.stderr)
if v.returncode:r['status']='native_failed';save();raise SystemExit(v.returncode)
e=json.loads(v.stdout);assert e['status']=='ok' and len(e['directions'])==2 and type(e['managed_used']) is int and e['managed_used']==0;r.update(status='complete_native_color_diagnostic',evidence=e);save();print(json.dumps(e['directions']))
