"""Native radius8 refinement of two frozen screen-copy starting models."""
import hashlib,json,subprocess,shutil
from pathlib import Path
root=Path('/Users/themoretheless/.codex/tmp/rrrah-dedup-copydays');b=Path('docs/research');h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();base=b/'dedup-screen-filter8.json';oracle=b/'dedup-sift-oracle-geometry.json';audit=b/'dedup-sift-oracle-geometry-audit.json';g=json.loads(oracle.read_text());ga=json.loads(audit.read_text());assert all(h(k)==v for k,v in ga['input_hashes'].items());initial=[json.loads(base.read_text())['evidence']['matrix'],next(v for v in g['results'] if v['case']=='screen')['evidence']['regions'][0]['matrix']]
input=b/'dedup-screen-original-refinement-work-input.txt';assert not input.exists();input.write_text(''.join(' '.join(str(v) for row in matrix for v in row)+'\n' for matrix in initial));exe=root/'projective-refinement-work-probe-screen';assert not exe.exists();shutil.copy2('target/debug/examples/projective_refinement_work_probe',exe)
left=root/'original-resolution-negative-200201/200500.jpg';right=root/'original-resolution-strong-all/200501.jpg';paths=[exe,left,right,base,oracle,audit,input,Path(__file__),Path('crates/rrrah-dedup/examples/projective_refinement_work_probe.rs'),Path('crates/rrrah-dedup/src/warp.rs')];pins={str(p):h(p) for p in paths};out=b/'dedup-screen-original-refinement-work.json';assert not out.exists();r={'status':'running_native','input_hashes':pins,'required_models':2,'registration_policy':{'radius':8,'stride':16,'rounds':16,'max_sample_pairs':180000000},'scope':'Original-resolution native pixel-based planar refinement of baseline and first SIFT model. Encoded fitted objective with unchanged gain/offset bounds, original final residual thresholds unchanged. No final acceptance, broad precision or complete allocation bound.'}
def save():
 tmp=out.with_suffix('.tmp');tmp.write_text(json.dumps(r,indent=2)+'\n');tmp.replace(out)
save();v=subprocess.run([str(exe),str(left),str(right),str(input)],capture_output=True,text=True);r.update(returncode=v.returncode,stdout=v.stdout,stderr=v.stderr);assert all(h(k)==v for k,v in pins.items())
if v.returncode:r['status']='native_failed';save();raise SystemExit(v.returncode)
e=json.loads(v.stdout);assert e['status']=='ok' and len(e['models'])==2 and type(e['managed_used']) is int and e['managed_used']==0;r.update(status='complete_native_refinement',evidence=e);save()
