#!/usr/bin/env python3
"""Verify pinned PICT RGBA oracles, native admission and optional actual Metal transport."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--corpus', type=Path, required=True)
parser.add_argument('--target-dir', type=Path, required=True)
parser.add_argument('--report', type=Path, required=True)
parser.add_argument('--metal', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
args.report.parent.mkdir(parents=True, exist_ok=True)

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

manifests = [root / 'docs/research/pict-external-corpus-probe-2026-10-06.json',
             root / 'docs/research/pict-extended-corpus-oracle-2026-10-06.json']
records = {case['name']: case for manifest in manifests for case in json.loads(manifest.read_text())}
report = {'scope': 'Four pinned external packed PICT subsets and authored regression tests',
          'manifests': {str(p.relative_to(root)): sha(p) for p in manifests},
          'inputs': [], 'checks': [], 'limitations': [
              'Not universal PICT support or independent GPU color/physical HDR qualification.',
              'External producer attribution and redistribution licensing remain unresolved.',
              'Oracle files were generated by TwelveMonkeys 3.13.0; this gate checks their pinned bytes.']}
authored_manifest = root / 'tests/fixtures/pict/unpacked-manifest.json'
report['manifests'][str(authored_manifest.relative_to(root))] = sha(authored_manifest)
for case in json.loads(authored_manifest.read_text())['cases']:
    source = authored_manifest.parent / case['file']
    if sha(source) != case['source_sha256']:
        raise SystemExit(f'authored source mismatch: {case["file"]}')
    if ('xrgb' in case['file'] or case['file'] == 'drop-pad-rgb.pict') and (case.get('sips_exit') != 0
            or case.get('sips_dimensions') != [case['width'], case['height']]
            or case.get('sips_rgba8') != case['expected_rgba8']):
        raise SystemExit(f'recorded macOS pixel mismatch: {case["file"]}')
report['limitations'].append('Unpacked RGB555 independent decoders disagree; authored tests only. '
                             'Unpacked xRGB uses recorded macOS sips pixels, not a fresh oracle run.')
for name in ['mire16.pict', 'mire32.pict', '16bit.pict', '32bit.pict']:
    record = records[name]
    source = args.corpus / name
    oracle = args.corpus / (name + '.rgba')
    dimensions = tuple(map(int, record['oracle_stdout'].strip().split('x')))
    if (sha(source) != record['sha256'] or sha(oracle) != record['oracle_sha256']
            or oracle.stat().st_size != dimensions[0] * dimensions[1] * 4):
        raise SystemExit(f'pinned source/oracle mismatch: {name}')
    report['inputs'].append({'name': name, 'source_sha256': sha(source),
                             'oracle_sha256': sha(oracle), 'dimensions': dimensions})
environment = os.environ.copy()
environment['RRRAH_PICT_CORPUS'] = str(args.corpus.resolve())
checks = [('native', ['cargo', 'test', '-p', 'rrrah-decode', '--lib', 'pict::'],
           ['--include-ignored', '--nocapture'], 23)]
if args.metal:
    checks.append(('metal', ['cargo', 'test', '-p', 'rrrah', '--test', 'hdr_raster_swap', 'pict_'],
                   ['--ignored', '--nocapture'], 3))
for name, prefix, suffix, count in checks:
    command = prefix + ['--locked', '--target-dir', str(args.target_dir.resolve()), '--'] + suffix
    completed = subprocess.run(command, cwd=root, env=environment, capture_output=True, text=True, timeout=300)
    output = completed.stdout + completed.stderr
    log = args.report.with_name(args.report.stem + f'-{name}.log')
    log.write_text(output)
    passed = completed.returncode == 0 and f'{count} passed; 0 failed; 0 ignored' in output
    adapters = [line for line in output.splitlines() if line.startswith('PICT adapter:')]
    if name == 'metal':
        passed = passed and len(adapters) == 7 and all('Metal ' in line for line in adapters)
    report['checks'].append({'name': name, 'passed': passed, 'command': command,
                             'adapters': adapters, 'log': str(log), 'log_sha256': sha(log)})
report['passed'] = all(check['passed'] for check in report['checks'])
args.report.write_text(json.dumps(report, indent=2) + '\n')
print(json.dumps({'passed': report['passed'], 'report': str(args.report)}))
raise SystemExit(0 if report['passed'] else 1)
