"""Verify bounded original-point recheck against independently audited witnesses."""
import hashlib,json
from pathlib import Path
D=Path('docs/research');p=D/'dedup-main-local-rank-large-points.json';h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();r=json.loads(p.read_text());assert r['status']=='complete' and r['points']==1016 and r['maximum_points']==28000 and r['maximum_point_checks']==28000*28001//2 and len(r['results'])==r['required_regions']==14;assert all(h(k)==v for k,v in r['input_hashes'].items());base=json.loads((D/'dedup-main-all-photometric-local-rank.json').read_text());old=next(v for v in base['results'] if v['query']=='207401.jpg');audit_path=D/'dedup-main-all-photometric-local-rank-audit.json';audit=json.loads(audit_path.read_text());assert audit['status']=='verified_all_photometric_cached_local_rank_terminal' and any(x['query']=='207401.jpg' for x in audit['summary']);assert audit['pins']['docs/research/dedup-main-all-photometric-local-rank.json']==h(D/'dedup-main-all-photometric-local-rank.json');summary=[]
for row,previous in zip(r['results'],old['regions']):
 assert row['region_index']==previous['region_index'] and row['expected_witnesses']==len(previous['witness_indices']);assert row['returncode']==0 and row['evidence']==[json.loads(x) for x in row['stdout'].splitlines()];assert [x['filter_radius'] for x in row['evidence']]==[0,3,8]
 for e in row['evidence']:
  assert e['status']=='ok' and e['witnesses']==row['expected_witnesses'];assert len(e['directions'])==2
  for x in e['directions']:assert 0<=x['valid_sites']<=x['sites'] and 0<=x['agreeing_pairs']<=x['informative_pairs']<=8*x['valid_sites']
  passes=all(x['informative_pairs']>=1000 and x['valid_sites']/x['sites']>=.3 and x['agreeing_pairs']/x['informative_pairs']>=.9 for x in e['directions']);assert passes==e['supported']
  summary.append({'region_index':row['region_index'],'filter_radius':e['filter_radius'],'witnesses':e['witnesses'],'supported':passes})
result={'status':'verified_complete_original_point_budget_recheck','regions':14,'filter_cases':42,'supported_filter8_regions':sum(x['supported'] for x in summary if x['filter_radius']==8),'summary':summary,'pins':{str(x):h(x) for x in [p,audit_path,Path(__file__)]},'scope':'Original1016 points retained, independently audited witness counts, actual cached native API and unchanged support predicates. Budget increase only; no independent pixel oracle for new cases, broad precision/default promotion or full-image classification.'};out=D/'dedup-main-local-rank-large-points-audit.json';assert not out.exists();out.write_text(json.dumps(result,indent=2)+'\n');print(result['status'],result['supported_filter8_regions'])
